#!/usr/bin/env python3
# Generate unzx0_corpus.h: a set of ZX0 round-trip test vectors packed by the
# REFERENCE encoder (Einar Saukas's `zx0`, default forward/v2 mode -- the format
# our UnZX0 decodes). This makes the encoder the ground truth: the example
# decompresses each vector on-target and compares byte-exact to the original.
#
# LOCAL-ONLY regeneration tool. The generated header is committed; CI never runs
# this. It builds the encoder from z88dk's vendored ZX0 source if no `zx0` is on
# PATH (same code as github.com/einar-saukas/ZX0).
import os, subprocess, sys, tempfile, shutil, random

HERE = os.path.dirname(os.path.abspath(__file__))
Z88_SRC = "/home/remco/tools/z88dk/src/zx0"

def find_encoder():
    exe = shutil.which("zx0")
    if exe:
        return exe
    # build from vendored reference source
    out = os.path.join(tempfile.gettempdir(), "zx0ref_gen")
    srcs = [os.path.join(Z88_SRC, f) for f in
            ("zx0.c", "compress.c", "optimize.c", "memory.c")]
    if all(os.path.exists(s) for s in srcs):
        subprocess.run(["gcc", "-O2", "-o", out, *srcs], check=True)
        return out
    sys.exit("no `zx0` encoder on PATH and no vendored source at " + Z88_SRC)

def pack(enc, raw):
    with tempfile.TemporaryDirectory() as d:
        i = os.path.join(d, "i.bin"); o = os.path.join(d, "o.zx0")
        open(i, "wb").write(raw)
        subprocess.run([enc, "-f", i, o], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return open(o, "rb").read()

def carr(name, data):
    body = ",".join(str(b) for b in data)
    return f"static const u8 {name}[{len(data)}] = {{{body}}};\n"

def main():
    enc = find_encoder()
    # Realistic 4 KB block: reuse the committed benchmark corpus if present,
    # else a deterministic pseudo-random-but-structured fill.
    big_path = os.path.join(HERE, "..", "..", "benchmarks",
                            "zx0-decompress", "data", "raw.bin")
    if os.path.exists(big_path):
        big = open(big_path, "rb").read()
    else:
        rnd = random.Random(1234)
        big = bytes((rnd.randrange(256) if i % 7 else 0x20) for i in range(4096))

    # Corner cases (kept exactly).
    rnd = random.Random(99)
    vectors = [
        ("one",   bytes([0x42])),                       # single byte
        ("two",   bytes([0xAA, 0x55])),                 # two bytes
        ("same",  bytes([0xE3]) * 256),                 # all-same (long run)
        ("incmp", bytes(rnd.randrange(256) for _ in range(200))),  # incompressible
        ("tiles", bytes(([0x00,0x18,0x3C,0x7E,0x7E,0x3C,0x18,0x00] * 8) +
                        ([0xFF,0x81,0x81,0x81,0x81,0x81,0x81,0xFF] * 8)),),  # structured
        ("big",   big),                                 # realistic, many tokens
    ]

    # Fuzz-grade random vectors: deterministic seeds so the committed header is
    # stable, but a wide spread of sizes and two flavours -- pure-random (literal-
    # heavy, exercises the incompressible path) and "structured" (runs + repeats +
    # literals, exercises the LZ matcher and long back-references / overlaps).
    def gen_pure(seed, n):
        r = random.Random(seed)
        return bytes(r.randrange(256) for _ in range(n))

    def gen_struct(seed, n):
        r = random.Random(seed)
        out = bytearray()
        while len(out) < n:
            k = r.randrange(4)
            if k == 0:                                  # run of one byte
                out += bytes([r.randrange(256)]) * (1 + r.randrange(40))
            elif k == 1 and len(out) > 2:               # back-reference (copy earlier)
                off = 1 + r.randrange(min(len(out), 300))
                ln = 1 + r.randrange(40)
                base = len(out) - off
                for i in range(ln):
                    out.append(out[base + (i % off)])
            elif k == 2:                                # short literal burst
                out += bytes(r.randrange(256) for _ in range(1 + r.randrange(8)))
            else:                                       # repeated small motif
                motif = bytes(r.randrange(256) for _ in range(1 + r.randrange(4)))
                out += motif * (1 + r.randrange(20))
        return bytes(out[:n])

    # 12 pure-random (small, varied) + 12 structured (larger, packable) = 24 fuzz vectors.
    pure_sizes   = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
    struct_sizes = [17, 40, 64, 100, 128, 200, 256, 384, 500, 700, 900, 1200]
    for i, sz in enumerate(pure_sizes):
        vectors.append((f"pr{i:02d}", gen_pure(1000 + i, sz)))
    for i, sz in enumerate(struct_sizes):
        vectors.append((f"st{i:02d}", gen_struct(2000 + i, sz)))

    lines = [
        "// unzx0_corpus.h -- GENERATED by unzx0_corpus_gen.py (do not edit).",
        "// ZX0 round-trip vectors packed by the reference encoder; the oracle for",
        "// unzx0_01_roundtrip.c. Each entry: packed stream + original + length.",
        "#ifndef MVCZ80_UNZX0_CORPUS_H",
        "#define MVCZ80_UNZX0_CORPUS_H",
        "#include \"types.h\"",
        "",
    ]
    entries = []
    maxraw = 0
    for name, raw in vectors:
        packed = pack(enc, raw)
        maxraw = max(maxraw, len(raw))
        lines.append(carr(f"g_zx0_pk_{name}", packed))
        lines.append(carr(f"g_zx0_raw_{name}", raw))
        entries.append((name, len(raw)))
    lines.append(f"#define ZX0_CORPUS_MAXRAW {maxraw}")
    lines.append(f"#define ZX0_CORPUS_COUNT  {len(entries)}")
    lines.append("typedef struct { const u8* packed; const u8* raw; u16 len; } ZX0Vec;")
    lines.append("static const ZX0Vec g_zx0_corpus[ZX0_CORPUS_COUNT] = {")
    for name, ln in entries:
        lines.append(f"\t{{ g_zx0_pk_{name}, g_zx0_raw_{name}, {ln} }},")
    lines.append("};")
    lines.append("#endif")
    open(os.path.join(HERE, "unzx0_corpus.h"), "w").write("\n".join(lines) + "\n")
    print("wrote unzx0_corpus.h:", ", ".join(f"{n}={l}B" for n, l in entries))

if __name__ == "__main__":
    main()
