// Resident main — a complete, turnkey banked ROM. You write ordinary C: include the
// generated far.h and call far_<name>() to reach a function in another bank. Everything
// else -- the call thunks, the dispatch table, the ROM header, the slot select -- is
// generated by bankpack or provided by farrt.asm.
#include "types.h"
#include "far.h"

volatile u8 __at(0xE000) R[8];

void main(void)
{
	u16 score = far_play_level(3);   // resident -> gameplay bank -> scoring bank, automatic
	R[1] = (u8)score;
	R[2] = (u8)(score >> 8);
	// play_level(3) = level_score(3) + 50 = (3 * 100) + 50 = 350. The 3*100 runs a
	// runtime multiply (__mulint) served from the shared resident helper pool.
	R[0] = (score == 350) ? 0xA5 : 0x00;
}
