#!/usr/bin/env bash
# Acceptance test for ASCII-16 banking (MAPPER ASCII16): 16 KB segments, a bank
# carrying >8 KB of content (checksummed), the statics data model intact, on
# C-BIOS_MSX1 AND C-BIOS_MSX2 — plus "unknown mapper" asserted to fail the build.
set -uo pipefail
export SDL_VIDEODRIVER=dummy
DIR=$(cd "$(dirname "$0")" && pwd)
ROOT="$DIR"; while [ ! -f "$ROOT/lib/ext/farrt.asm" ] && [ "$ROOT" != / ]; do ROOT=$(dirname "$ROOT"); done
OMX="${OPENMSX:-$(command -v openmsx || echo /home/remco/tools/openmsx/bin/openmsx)}"
BP="$ROOT/tools/bankpack.sh"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT

cp "$ROOT/lib/gen/types.h" "$W/"
cp "$ROOT/lib/ext/farrt.asm" "$W/"
cp "$DIR/main.c" "$DIR/bankA.c" "$DIR/bankB.c" "$DIR/bank.manifest" "$W/"
cd "$W"

# 0. generate the >8 KB payload + its checksum (pattern is arbitrary but fixed)
awk 'BEGIN{
  n=9000; printf "// generated by run.sh -- do not edit\n";
  printf "#define BIG_LEN %du\n", n;
  s=0; for(i=0;i<n;i++){ b=(i*7+3)%251; s=(s+b)%65536 }
  printf "#define BIG_EXPECTED %du\n", s;
  printf "#ifdef BIG_TABLE_DEFINE\nconst unsigned char big_table[%d] = {\n", n;
  for(i=0;i<n;i++){ printf "%d,", (i*7+3)%251; if(i%20==19) printf "\n" }
  printf "};\n#else\nextern const unsigned char big_table[%d];\n#endif\n", n
}' > bank_big.h
printf '#define BIG_TABLE_DEFINE\n#include "bank_big.h"\n' > bank_big.c

# 1. generate far.h + thunks; compile / assemble everything
bash "$BP" --gen bank.manifest . || { echo "GEN FAIL"; exit 1; }
sdasz80 -o farrt.rel farrt.asm                       || { echo "ASM farrt FAIL"; exit 1; }
sdasz80 -o _bp_far_thunks.rel _bp_far_thunks.asm     || { echo "ASM thunks FAIL"; exit 1; }
for c in main bankA bankB bank_big; do
  sdcc -c -mz80 --sdcccall 1 -I. -o "$c.rel" "$c.c"  || { echo "CC $c FAIL"; exit 1; }
done
# the big table links into bankA's segment
sed -i 's/bankA.rel/bankA.rel bank_big.rel/' bank.manifest

# 2. build the ROM
bash "$BP" bank.manifest game.rom 64 || { echo "BANKPACK FAIL"; exit 2; }

# 3. run on both machine generations
MEND=$(awk '$1=="DEF" && $2=="_mark_end"{print $3}' _bp_resident.noi)
[ -n "$MEND" ] || { echo "no _mark_end"; exit 2; }
fail=0
for MACHINE in C-BIOS_MSX1 C-BIOS_MSX2; do
  TCL=$(mktemp)
  cat > "$TCL" <<TCL
set renderer none
set scheduler_mode fast
set throttle off
after realtime 25 { puts stderr "OUT=TIMEOUT"; exit 1 }
carta $W/game.rom -romtype ASCII16
debug set_bp $MEND {} {
  set b {}
  for {set i 0} {\$i < 8} {incr i} { lappend b [format %02x [debug read memory [expr {0xE000+\$i}]]] }
  puts stderr "OUT=RES=[join \$b {}]"
  exit 0
}
TCL
  RAW=$(timeout 30 "$OMX" -machine "$MACHINE" -script "$TCL" 2>&1 | sed -n 's/.*OUT=//p')
  rm -f "$TCL"
  RES=$(echo "$RAW" | sed -n 's/^RES=\([0-9a-f]*\).*/\1/p' | head -1)
  if [ "${RES:0:2}" = "a5" ]; then
    echo "  $MACHINE: PASS  R[]=$RES"
  else
    echo "  $MACHINE: FAIL  R[]=${RES:-<none>} ($RAW)"; fail=1
  fi
done

# 4. negative: an unknown mapper must be a build error
sed 's/^MAPPER .*/MAPPER ASCII12/' bank.manifest > bank.bad.manifest
if bash "$BP" bank.bad.manifest bad.rom 64 >/dev/null 2>&1; then
  echo "  unknown mapper: FAIL (build was accepted)"; fail=1
else
  echo "  unknown mapper: PASS (build rejected)"
fi

[ "$fail" -eq 0 ] && { echo "  RESULT: PASS"; exit 0; } || { echo "  RESULT: FAIL"; exit 1; }
