// moonblaster_wave_bin.h -- GENERATED by tools/mbwblob.sh. DO NOT EDIT.
// Source: lib/ext/moonblaster_wave_player.asm, resident-song configuration
// (selbank_FE/curbank_FE/start_mus_cnt -> RET). sha256(payload) = cbd2064248dc82b83b7c3032f0fae64c090d267e1e071eb27f13db989feb87e8
// Interface only: #defines + a forward declaration of the blob. The blob DATA
// lives in moonblaster_wave_bin_data.h, #included at the BOTTOM of the .c so it
// links above the wrappers (which Init's copy-to-0x4000 must not overwrite).
#ifndef MSXMVL_EXT_MOONBLASTER_WAVE_BIN_H
#define MSXMVL_EXT_MOONBLASTER_WAVE_BIN_H

#define MBWAVE_ORG        0x4000u   // load address (16 KB replayer, 0x4000-0x7E8D)
#define MBWAVE_SIZE       16013u  // bytes to copy from the blob to MBWAVE_ORG

// replayer interface (fixed addresses; workspace is at 0xDA00, above the code)
#define MBWAVE_START      0x454Au  // call: init OPL4 + song, begin (no hook)
#define MBWAVE_STOP       0x462Du  // call: stop/pause, silence
#define MBWAVE_CONT       0x4621u  // call: continue after stop/pause
#define MBWAVE_PLAYINT    0x4669u  // the per-interrupt replay routine
#define MBWAVE_OLDINT     0x4721u  // play_int chain tail (module writes RET here)
#define MBWAVE_BUSY       0xDA00u  // u8: 0=silent, nonzero=playing
#define MBWAVE_SONGADR    0xDA04u  // u16: song body address (file+6)
#define MBWAVE_BANK1      0xDA01u  // u8: song mapper segment (resident: unused)
#define MBWAVE_POS        0xDA06u  // u8: current position
#define MBWAVE_STEP       0xDA07u  // u8: current step in the pattern

extern const unsigned char MBWAVE_BIN[MBWAVE_SIZE];  // defined in *_bin_data.h

#endif // MSXMVL_EXT_MOONBLASTER_WAVE_BIN_H
