// msxmvl EXTENSION module: moonblaster_wave -- C wrapper over the MBWave replayer.
// The replayer is moonblaster_wave_player.asm, pre-assembled into moonblaster_wave_bin.h
// (generated by tools/mbwblob.sh). This file relocates it into RAM and drives its
// original entry points. See moonblaster_wave.h for the memory contract.
#include "types.h"
#include "moonblaster_wave.h"
#include "moonblaster_wave_bin.h"

#define MBW_VAR(a)   (*(volatile u8*)(a))
#define MBW_CALL(a)  mbw_call((void (*)(void))(a))

// Every replayer entry (start/stop/cont, and play_int itself) was designed to be
// reached from the BIOS ISR, which saves ALL registers first -- so the replayer
// clobbers IX/IY freely. SDCC uses IX as its frame pointer, so a bare call from C
// would corrupt it. Save IX/IY around the call.
static void mbw_call(void (*fn)(void)) __naked
{
	(void)fn;   // in HL (sdcccall 1)
	__asm
	push ix
	push iy
	ld de, #00001$
	push de
	jp (hl)
00001$:
	pop iy
	pop ix
	ret
	__endasm;
}

void MoonBlasterWave_Init(void)
{
	// Copy the 16 KB replayer to 0x4000. The blob lives in this program's own image,
	// which under MSX-DOS (.COM at 0x0100) extends ABOVE 0x4000 -- so source and
	// destination overlap with dst > src. A forward copy would corrupt the tail; copy
	// BACKWARD instead, exactly as the resident loader does.
	{
		const u8* src = MBWAVE_BIN + MBWAVE_SIZE - 1;
		u8* dst = (u8*)(MBWAVE_ORG + MBWAVE_SIZE - 1);
		u16 n = MBWAVE_SIZE;
		while (n--) *dst-- = *src--;             // backward copy (dst > src overlap-safe)
	}
	// clear the replayer's RW workspace (play_busy..+30 at 0xDA00), as its loader does
	{
		u8* w = (u8*)MBWAVE_BUSY;
		u8 i = 31;
		while (i--) *w++ = 0;
	}
}

void MoonBlasterWave_Start(const void* song)
{
	// Init the OPL4 + voices + song and mark it playing. This build does NOT install a
	// BIOS interrupt hook: under MSX-DOS the interrupt runs in a slot context where the
	// replayer's own interslot H.TIMI hook faults (page 0 is RAM, so RST 30h is invalid),
	// and a plain hook can't reach the replayer's slot either. So playback is DRIVEN BY
	// THE CALLER via MoonBlasterWave_Tick() -- reliable on DOS and ROM alike. (A ROM game
	// that wants fire-and-forget interrupt playback can install its own H.TIMI hook that
	// calls MoonBlasterWave_Tick.)
	MoonBlasterWave_Stop();                          // stop any current song first
	// end play_int's chain in a clean RET (old_int == play_int_end), so a tick returns
	// straight to Tick's caller instead of into a stale/absent hook chain.
	*(volatile u8*)MBWAVE_OLDINT = 0xC9;             // RET
	// point at the song body: .MWM files begin with a 6-byte "MBMS"+type header
	*(volatile u16*)MBWAVE_SONGADR = (u16)song + 6;
	MBW_CALL(MBWAVE_START);                          // init OPL4 + voices + song, mark playing
}

void MoonBlasterWave_Stop(void)     { MBW_CALL(MBWAVE_STOP); }
void MoonBlasterWave_Continue(void) { MBW_CALL(MBWAVE_CONT); }

u8 MoonBlasterWave_IsPlaying(void) { return MBW_VAR(MBWAVE_BUSY); }
u8 MoonBlasterWave_Position(void)  { return MBW_VAR(MBWAVE_POS); }
u8 MoonBlasterWave_Step(void)      { return MBW_VAR(MBWAVE_STEP); }

void MoonBlasterWave_Tick(void)
{
	// One interrupt's worth, exactly as the BIOS ISR would deliver it. mbw_call saves
	// IX/IY (the replayer clobbers them); DI first and leave interrupts masked on return
	// so a run of ticks is deterministic -- issue EI yourself to hand back to the BIOS.
	__asm di __endasm;
	MBW_CALL(MBWAVE_PLAYINT);
}

// The 16 KB replayer blob is defined LAST, on purpose. Init relocates it to 0x4000, and
// under MSX-DOS the .COM image extends past 0x4000 -- so if the blob were placed among
// the functions above, that copy would overwrite the very wrappers that drive it. Defined
// here (bottom of the translation unit) it links above every wrapper, all of which stay
// below 0x4000 and survive the copy. Keep this include at the end of the file.
#include "moonblaster_wave_bin_data.h"
