// msxmvl EXTENSION module: moonblaster_wave -- the MoonBlaster for MoonSound *Wave*
// (OPL4 / YMF278B wavetable) replayer.
//
// Plays MoonBlaster Wave songs (.MWM) on a MoonSound cartridge through the original
// MBWave 1.01 replayer. Unlike the MoonBlaster 1.4 module (which was interrupt-time-
// optimised), this replayer is shipped AS-IS: it is already efficient (measured
// ~190-4514 T-states/interrupt across the 32-song Jer Der Wave corpus -- at 60 Hz a
// frame is ~59000 T, so even the densest song is well within budget). So the msxmvl
// contribution here is integration + measurement + a C API, not a T-state beat.
//
// Provenance: MBWave and its replayer are by this library's author (Moonsoft);
// original GEN80 source, mechanically converted (tools/gen2pasmo.py) and relicensed
// here under the repo's MIT license. Source: moonblaster_wave_player.asm; the checked-in
// binary moonblaster_wave_bin.h is generated by tools/mbwblob.sh.
//
// THE MEMORY CONTRACT (read before using):
//   - MoonBlasterWave_Init copies the 16 KB replayer to its home 0x4000-0x7E8D, and its
//     RW workspace lives at 0xDA00. Your program must not place code/data in either
//     region. Under MSX-DOS a .COM (loads at 0x0100) must end below 0x4000; a ROM game
//     must copy the replayer into RAM at 0x4000 (page-1 RAM via slot switching) since
//     the replayer self-modifies (it patches its own H.TIMI interslot slot byte) and so
//     cannot execute from ROM.
//   - The .MWM song must stay RESIDENT in the visible 64 KB while it plays: this is the
//     resident-song build (the replayer's mapper page switches are neutralised), so it
//     performs no bank switching. Keep the song where you pass it, interrupts-visible.
//   - Playback runs on the BIOS 50/60 Hz interrupt via the H.TIMI hook (0xFD9F), which
//     MoonBlasterWave_Start installs (chaining) and MoonBlasterWave_Stop removes.
//   - Under MSX-DOS, write the MSX-version byte before Start:  *(u8*)0x002D = 0;
//     (page 0 is RAM there, so the BIOS byte the replayer reads is garbage). ROM: nothing.
//   - Needs a MoonSound (OPL4). The replayer initialises the chip itself -- no other
//     module required.
#ifndef MSXMVL_EXT_MOONBLASTER_WAVE_H
#define MSXMVL_EXT_MOONBLASTER_WAVE_H

#include "types.h"

// Function: MoonBlasterWave_Init
// Copy the replayer to its home at 0x4000 and clear its workspace. Call once, first.
void MoonBlasterWave_Init(void);

// Function: MoonBlasterWave_Start
// Start a song: points the replayer at it (skipping the 6-byte "MBMS" file header),
// initialises the OPL4, installs the H.TIMI hook and begins on the next interrupt.
//   song - the .MWM file in memory (must stay resident while playing)
void MoonBlasterWave_Start(const void* song);

// Function: MoonBlasterWave_Stop
// Stop/pause: silence the OPL4 and remove the hook. Continue resumes where it stopped.
void MoonBlasterWave_Stop(void);

// Function: MoonBlasterWave_Continue
// Resume a stopped/paused song where it left off.
void MoonBlasterWave_Continue(void);

// Function: MoonBlasterWave_IsPlaying
// Nonzero while a song plays, 0 after it ends or is stopped.
u8 MoonBlasterWave_IsPlaying(void);

// Function: MoonBlasterWave_Position
// Current position in the song's position list.
u8 MoonBlasterWave_Position(void);

// Function: MoonBlasterWave_Step
// Current step within the playing pattern.
u8 MoonBlasterWave_Step(void);

// Function: MoonBlasterWave_Tick
// Advance playback by one interrupt's worth without the BIOS: masks interrupts (DI) and
// calls the replayer directly. Interrupts STAY masked on return (issue EI to hand
// playback back to the BIOS). For fast-forward, rendering, or driving music yourself.
void MoonBlasterWave_Tick(void);

#endif // MSXMVL_EXT_MOONBLASTER_WAVE_H
