#!/usr/bin/env bash
# bankpack -- turnkey ASCII-8 MegaROM builder for banked code.
#
# Pure bash + SDCC toolchain + coreutils (no Python). Two modes:
#
#   bankpack.sh --gen <manifest> [outdir]      generate far.h + far thunks
#   bankpack.sh <manifest> <out.rom> [rom_kb]  link banks + assemble the ROM
#
# The developer writes plain C and a manifest. `--gen` emits, from the manifest's
# FAR lines, a header of far-call declarations (callers just `#include "far.h"`
# and call `far_<name>(...)`) and the resident thunks + dispatch table. The build
# mode links each bank at its window address, patches the dispatch table with the
# real function addresses, and assembles the 64 KB ROM.
#
# Manifest (whitespace; '#' comments; blank lines ignored):
#   SEG   RUN      OBJ [OBJ ...]      one bank per line; first line = RESIDENT
#   FAR   SEG      <C prototype>      declare a far-callable function in SEG
#     e.g.  FAR 5 u16 farA(u16 x)
#   FARTAB base slot0 slot1 ...       (advanced/manual; auto-derived from FAR)
#
# Far-call convention (SDCC --sdcccall 1): args must be REGISTER-passed
# (16-bit/pointer in HL/DE/BC) and returns 16-bit/pointer/void (HL/DE). The thunk
# preserves those plus IX; it clobbers only A/F. Avoid u8/bool/char args/returns
# (they ride in A) and >~3 args (spill to the stack) -- use u16.
set -uo pipefail

SEGSIZE=8192
ADDR_BANK2=0x7000        # ASCII-8 bank-2 select (must match farrt.asm)
SHADOW=0xE020            # memseg shadow RAM byte  (must match farrt.asm)
WINDOW=0x8000           # page-2 window base: banked code runs here, resident below

die() { echo "bankpack: $*" >&2; exit 1; }

# Locate SDCC's z80 runtime library (for *, /, long, float helpers). Override
# with $BANKPACK_Z80LIB. Empty if not found -> resident helper pool is skipped
# (fine for banks that use no such operations).
find_z80lib() {
  local c
  for c in "${BANKPACK_Z80LIB:-}" \
           /usr/share/sdcc/lib/z80/z80.lib \
           /usr/lib/sdcc/lib/z80/z80.lib \
           /usr/local/share/sdcc/lib/z80/z80.lib; do
    [ -n "$c" ] && [ -f "$c" ] && { echo "$c"; return; }
  done
}

# ---- shared manifest parse: fills SEGS/RUNS/OBJS, FAR_SEG/FAR_NAME/FAR_PROTO, FARTAB ----
parse_manifest() {
  SEGS=(); RUNS=(); OBJS=(); FAR_SEG=(); FAR_NAME=(); FAR_PROTO=(); FARTAB=""
  local a b rest
  while read -r a b rest; do
    [ -z "${a:-}" ] && continue
    case "$a" in \#*) continue;; esac
    case "$a" in
      FAR)
        # b = segment, rest = C prototype; name = identifier just before '('
        local name; name=$(printf '%s' "$rest" | sed 's/(.*//' | awk '{print $NF}')
        [ -n "$name" ] || die "cannot parse function name from: FAR $b $rest"
        FAR_SEG+=("$b"); FAR_NAME+=("$name"); FAR_PROTO+=("$rest") ;;
      FARTAB)
        FARTAB="$b $rest" ;;
      *)
        [ -n "$b" ] && [ -n "$rest" ] || die "bad manifest line: $a $b $rest"
        SEGS+=("$a"); RUNS+=("$b"); OBJS+=("$rest") ;;
    esac
  done < <(sed 's/#.*//' "$1")
}

# =====================================================================
# --gen : emit far.h + _bp_far_thunks.asm from the FAR lines
# =====================================================================
if [ "${1:-}" = "--gen" ]; then
  MANIFEST="${2:?usage: bankpack.sh --gen <manifest> [outdir]}"
  OUTDIR="${3:-.}"
  parse_manifest "$MANIFEST"
  [ "${#FAR_NAME[@]}" -ge 1 ] || die "--gen: manifest has no FAR lines"

  H="$OUTDIR/far.h"; T="$OUTDIR/_bp_far_thunks.asm"
  {
    echo "// generated by 'bankpack --gen' -- do not edit"
    echo "#ifndef BANKPACK_FAR_H"
    echo "#define BANKPACK_FAR_H"
    echo '#include "types.h"'
    for i in "${!FAR_NAME[@]}"; do
      # prefix the function name with far_ in its prototype
      printf 'extern %s;\n' \
        "$(printf '%s' "${FAR_PROTO[$i]}" | sed 's/\([A-Za-z_][A-Za-z0-9_]*\)[[:space:]]*(/far_\1(/')"
    done
    echo "#endif"
  } > "$H"

  {
    echo ";; generated by 'bankpack --gen' -- do not edit"
    echo "	ADDR_BANK2 = $ADDR_BANK2"
    echo "	SHADOW     = $SHADOW"
    echo "	.globl _fartab"
    for n in "${FAR_NAME[@]}"; do echo "	.globl _far_$n"; done
    echo "	.area _CODE"
    # self-contained JP-(IX) helper (kept in this module to avoid sdld's
    # 'definition must follow reference' cross-module ordering quirk)
    echo "_far_jp_ix:"
    echo "	jp (ix)"
    for i in "${!FAR_NAME[@]}"; do
      n="${FAR_NAME[$i]}"; seg="${FAR_SEG[$i]}"; slot=$(( i * 2 ))
      cat <<ASM
_far_$n:
	push ix
	ld a,(SHADOW)
	push af
	ld a,#$seg
	ld (SHADOW),a
	ld (ADDR_BANK2),a
	ld ix,(_fartab + $slot)
	call _far_jp_ix
	pop af
	ld (SHADOW),a
	ld (ADDR_BANK2),a
	pop ix
	ret
ASM
    done
    echo "_fartab:"
    for n in "${FAR_NAME[@]}"; do echo "	.dw 0	; -> _$n"; done
  } > "$T"

  echo "bankpack --gen: wrote $H and $T (${#FAR_NAME[@]} far function(s))"
  exit 0
fi

# =====================================================================
# build : link banks + assemble ROM
# =====================================================================
MANIFEST="${1:?usage: bankpack.sh <manifest> <out.rom> [rom_kb]}"
OUT="${2:?usage: bankpack.sh <manifest> <out.rom> [rom_kb]}"
ROM_KB="${3:-64}"
parse_manifest "$MANIFEST"
[ "${#SEGS[@]}" -ge 1 ] || die "manifest has no banks"

# If FAR lines exist, the generated thunks belong in the resident bank, and the
# dispatch table is auto-derived (base _fartab, slots _<name> in FAR order).
if [ "${#FAR_NAME[@]}" -ge 1 ]; then
  [ -f _bp_far_thunks.rel ] || die "run 'bankpack --gen' + assemble _bp_far_thunks.asm first"
  OBJS[0]="${OBJS[0]} _bp_far_thunks.rel"
  if [ -z "$FARTAB" ]; then
    FARTAB="_fartab"
    for n in "${FAR_NAME[@]}"; do FARTAB="$FARTAB _$n"; done
  fi
fi

link_bank() {  # <run> <base> <input-rels-and--g-opts...>
  local run="$1" base="$2"; shift 2
  # NB: sdld's FIRST file arg is the OUTPUT basename (-> <base>.ihx/.map/.noi);
  # everything after it is an input. Pass an explicit output so no input .rel is
  # swallowed as the output name.
  sdldz80 -i -m -j -b _CODE="$run" "$base" "$@" >/dev/null 2>&1 || die "link failed (run $run)"
  [ -f "$base.ihx" ] || die "link produced no $base.ihx (unresolved symbol? run $run)"
}

place() {  # <seg> <base>
  local seg="$1" base="$2" bin="$2.bin" sz
  sdobjcopy -I ihex -O binary "$base.ihx" "$bin" || die "objcopy failed: $base"
  sz=$(stat -c%s "$bin")
  [ "$sz" -le "$SEGSIZE" ] || die "bank (seg $seg) is $sz B > segment size $SEGSIZE"
  dd if="$bin" of="$OUT" bs=1 seek="$((seg * SEGSIZE))" conv=notrunc status=none
  printf "bankpack: seg %-3s <- %-18s (%d B, file @ 0x%04x)\n" "$seg" "$base.ihx" "$sz" "$((seg * SEGSIZE))"
}

# 0. resident helper pool: collect every SDCC runtime helper (__mulint, __divs*,
# __mullong, float, ...) referenced by ANY bank, force those into the RESIDENT
# bank (page 1, always mapped) so they exist once and are shared -- no per-bank
# duplication, no bank switch to reach them. The per-bank -g injection (step 3)
# then resolves each bank's reference to the resident copy.
RES_EXTRA=()
declare -A HELPER=()
for i in "${!SEGS[@]}"; do
  for obj in ${OBJS[$i]}; do
    [ -f "$obj" ] || continue
    while read -r name; do HELPER["$name"]=1; done \
      < <(awk '$1=="S" && $3 ~ /^Ref/ && $2 ~ /^__/ {print $2}' "$obj")
  done
done
if [ "${#HELPER[@]}" -ge 1 ]; then
  Z80LIB="$(find_z80lib)"
  [ -n "$Z80LIB" ] || die "banks reference runtime helpers (${!HELPER[*]}) but z80.lib not found; set BANKPACK_Z80LIB"
  {
    echo ";; generated by bankpack -- forces runtime helpers into the resident pool"
    for h in "${!HELPER[@]}"; do echo "	.globl $h"; done
    echo "	.area _CODE"
    echo "_bp_helper_refs:"          # a reference table forces sdld to pull each
    for h in "${!HELPER[@]}"; do echo "	.dw $h"; done
  } > _bp_helpers.asm
  sdasz80 -o _bp_helpers.rel _bp_helpers.asm || die "assembling helper refs failed"
  RES_EXTRA=( _bp_helpers.rel -k "$(dirname "$Z80LIB")" -l "$(basename "$Z80LIB")" )
  echo "bankpack: resident helper pool: ${!HELPER[*]}"
fi

# 1. resident bank: link, record exported symbols (full names from .noi)
link_bank "${RUNS[0]}" "_bp_resident" ${OBJS[0]} "${RES_EXTRA[@]}"
declare -A RSYM=()
while read -r kw name val; do [ "$kw" = "DEF" ] && RSYM["$name"]="$val"; done < _bp_resident.noi
echo "bankpack: resident exports ${#RSYM[@]} symbol(s)"

# 2. ROM image filled with 0xFF; place resident
tr '\000' '\377' < /dev/zero | head -c "$((ROM_KB * 1024))" > "$OUT"
place "${SEGS[0]}" "_bp_resident"

# 3. link + place each remaining bank, injecting only referenced resident symbols
for i in $(seq 1 $(( ${#SEGS[@]} - 1 )) ); do
  base="_bp_bank${SEGS[$i]}"
  gopts=()
  for obj in ${OBJS[$i]}; do
    while read -r name; do
      [ -n "${RSYM[$name]:-}" ] && gopts+=( -g "$name=${RSYM[$name]}" )
    done < <(awk '$1=="S" && $3 ~ /^Ref/ {print $2}' "$obj")
  done
  link_bank "${RUNS[$i]}" "$base" ${OBJS[$i]} "${gopts[@]}"
  [ "${#gopts[@]}" -gt 0 ] && echo "bankpack: seg ${SEGS[$i]} resolved ${gopts[*]}"
  place "${SEGS[$i]}" "$base"
done

# 4. patch the dispatch table (bank->bank calls) into the ROM image
if [ -n "$FARTAB" ]; then
  declare -A ALLSYM=()
  for f in _bp_*.noi; do
    while read -r kw name val; do [ "$kw" = "DEF" ] && ALLSYM["$name"]="$val"; done < "$f"
  done
  set -- $FARTAB
  base_sym="$1"; shift
  base_addr="${ALLSYM[$base_sym]:-}"; [ -n "$base_addr" ] || die "FARTAB base '$base_sym' not found"
  base_off=$(( SEGS[0] * SEGSIZE + (base_addr - RUNS[0]) ))
  slot=0
  for sym in "$@"; do
    addr="${ALLSYM[$sym]:-}"; [ -n "$addr" ] || die "FARTAB slot symbol '$sym' not found"
    off=$(( base_off + slot * 2 ))
    lo=$(( addr & 0xFF )); hi=$(( (addr >> 8) & 0xFF ))
    printf "$(printf '\\x%02x\\x%02x' "$lo" "$hi")" | dd of="$OUT" bs=1 seek="$off" conv=notrunc status=none
    printf "bankpack: fartab[%d] = %-14s 0x%04x (file @ 0x%04x)\n" "$slot" "$sym" "$addr" "$off"
    slot=$((slot + 1))
  done
fi

# 5. safety checks (link-map): enforce the invariants banking relies on.
if [ "${#FAR_NAME[@]}" -ge 1 ]; then
  declare -A CHKSYM=()
  for f in _bp_*.noi; do
    while read -r kw name val; do [ "$kw" = "DEF" ] && CHKSYM["$name"]="$val"; done < "$f"
  done
  problems=0
  for n in "${FAR_NAME[@]}"; do
    th="${CHKSYM[_far_$n]:-}"; tg="${CHKSYM[_$n]:-}"
    # thunk must be resident (below the window); target must be IN the window
    if [ -n "$th" ] && [ "$((th))" -ge "$((WINDOW))" ]; then
      echo "bankpack: CHECK FAIL: thunk _far_$n at $th is not resident (>= window $WINDOW)" >&2; problems=$((problems+1))
    fi
    if [ -n "$tg" ] && [ "$((tg))" -lt "$((WINDOW))" ]; then
      echo "bankpack: CHECK FAIL: far target _$n at $tg is not in the window (< $WINDOW)" >&2; problems=$((problems+1))
    fi
  done
  # advisory: scan the resident binary for a direct call/jp into the window
  # range [0x8000,0xBFFF] -- such a branch would bypass a thunk and jump into
  # whatever segment happens to be mapped. Heuristic (may alias const data).
  hits=$(od -An -tu1 -v _bp_resident.bin 2>/dev/null | awk -v base="$((RUNS[0]))" '
    BEGIN{ split("195 205 194 202 210 218 226 234 242 250 196 204 212 220 228 236 244 252", O); for(i in O) op[O[i]]=1 }
    { for(i=1;i<=NF;i++){ b[n++]=$i } }
    END{ for(i=0;i<n-2;i++){ if(op[b[i]]){ a=b[i+1]+256*b[i+2]; if(a>=32768 && a<=49151) printf "0x%04x->0x%04x ", base+i, a } } }')
  [ -n "$hits" ] && echo "bankpack: CHECK WARN (heuristic): resident branch into window: $hits"
  [ "$problems" -eq 0 ] && echo "bankpack: safety checks OK (${#FAR_NAME[@]} thunk/target pair(s) verified)" \
                        || die "$problems safety-check failure(s)"
fi

echo "bankpack: wrote $OUT ($((ROM_KB)) KB, $((ROM_KB / 8)) x 8 KB segments)"
