#!/usr/bin/env python3
# gentables.py -- mvcz80 asset pipeline (Category D3): generate fixed-point maths
# tables (sine, cosine, arctangent) as C arrays for Z80 use. The MSX/demo-scene idiom
# is a "binary angle": one full turn is `entries` steps (default 256, so an angle fits
# in a u8 and wraps for free), and trig values are scaled to a signed integer.
#
# Deterministic, dependency-light (pure Python, no numpy), golden-tested. Companion to
# img2tiles/img2bitmap; emits types.h-compatible arrays.
#
#   gentables.py sin  <name> [entries] [amp]   signed sine, amp*sin(2*pi*i/entries)
#   gentables.py cos  <name> [entries] [amp]   signed cosine (sin shifted a quarter)
#   gentables.py atan <name> [entries]         angle (brads) for slope i/entries in [0,1)
#
# amp defaults to 127 -> values fit i8 (the compact classic table); amp>127 -> i16.
import sys, math

def carr(ctype, name, data):
    return f"const {ctype} {name}[{len(data)}]={{{','.join(str(v) for v in data)}}};\n"

def gen_sin(entries, amp, phase):
    # phase in steps: cos = sin shifted by a quarter turn (entries/4).
    vals = [round(amp * math.sin(2 * math.pi * ((i + phase) % entries) / entries))
            for i in range(entries)]
    ctype = "i8" if amp <= 127 else "i16"
    return ctype, vals

def gen_atan(entries):
    # index i represents slope = i/entries in [0,1) i.e. [0deg,45deg); value is the
    # angle in the same binary-angle unit (brads): atan(slope)/(2*pi)*entries.
    vals = [round(math.atan(i / entries) / (2 * math.pi) * entries) for i in range(entries)]
    return "u8", vals

def main():
    if len(sys.argv) < 3:
        sys.exit("usage: gentables.py <sin|cos|atan> <name> [entries] [amp]")
    kind, name = sys.argv[1], sys.argv[2]
    entries = int(sys.argv[3]) if len(sys.argv) > 3 else 256
    amp = int(sys.argv[4]) if len(sys.argv) > 4 else 127
    if entries <= 0:
        sys.exit("entries must be positive")
    U = name.upper()
    if kind == "sin":
        ctype, vals = gen_sin(entries, amp, 0)
        note = f"sine, amplitude {amp}"
    elif kind == "cos":
        ctype, vals = gen_sin(entries, amp, entries // 4)
        note = f"cosine, amplitude {amp}"
    elif kind == "atan":
        ctype, vals = gen_atan(entries)
        note = "arctangent: slope i/entries in [0,1) -> angle in brads"
    else:
        sys.exit("kind must be sin, cos or atan")
    out = name + "_table.h"
    lines = [
        f"// {out} -- GENERATED by gentables.py ({kind}) (do not edit).",
        f"// {note}; {entries} entries (one turn = {entries} steps).",
        '#include "types.h"', "",
        carr(ctype, name, vals),
        f"#define {U}_ENTRIES {entries}",
    ]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {kind} {ctype}[{entries}] ({note})")

if __name__ == "__main__":
    main()
