#!/usr/bin/env python3
# img2tiles.py -- mvcz80 asset pipeline (Category D1): convert a PNG image into an
# MSX SCREEN 2 (GRAPHIC 2) tileset -- pattern table + color table -- with a
# de-duplicated name table (tilemap). Emits C arrays (types.h compatible).
#
# SCREEN 2 tile format (TMS9918): each 8x8 tile is 8 pattern bytes (1 bit/pixel:
# 1=foreground, 0=background) + 8 colour bytes (per pixel-row: high nibble =
# foreground colour, low nibble = background colour, from the 16-colour palette).
# The hardware constraint is at most 2 colours per 8-pixel row; this tool enforces
# it by reducing each row to its two most-used palette colours.
#
# Minimal + deterministic + dependency-light (Python + Pillow). No vendored SDK.
# Usage: img2tiles.py <in.png> <name> [out.h] [--zx0]   (image width/height must be /8)
# --zx0 emits pattern/colour/nametable ZX0-packed (unpack on-target with UnZX0);
# compression is host-side (see zx0pack.py), the MSX only unpacks.
import sys
import zx0pack
from PIL import Image

# Standard TMS9918 16-colour palette (RGB). Index 0 = transparent (treated as black).
PALETTE = [
    (0, 0, 0), (0, 0, 0), (33, 200, 66), (94, 220, 120),
    (84, 85, 237), (125, 118, 252), (212, 82, 77), (66, 235, 245),
    (252, 85, 84), (255, 121, 120), (212, 193, 84), (230, 206, 128),
    (33, 176, 59), (201, 91, 186), (204, 204, 204), (255, 255, 255),
]

def nearest(rgb):
    r, g, b = rgb[:3]
    return min(range(16), key=lambda i: (r-PALETTE[i][0])**2 + (g-PALETTE[i][1])**2 + (b-PALETTE[i][2])**2)

def tile_bytes(px, tx, ty):
    """Return (pattern[8], colour[8]) for the 8x8 tile at (tx,ty), enforcing the
    2-colours-per-row rule (fg = most-used, bg = second, others snapped to nearest)."""
    pat, col = [], []
    for row in range(8):
        idxs = [nearest(px[tx*8 + c, ty*8 + row]) for c in range(8)]
        counts = {}
        for i in idxs:
            counts[i] = counts.get(i, 0) + 1
        order = sorted(counts, key=lambda i: (-counts[i], i))
        fg = order[0]
        bg = order[1] if len(order) > 1 else (0 if fg != 0 else 1)
        # snap each pixel to fg or bg (nearest of the two)
        def snap(i):
            df = sum((PALETTE[i][k]-PALETTE[fg][k])**2 for k in range(3))
            db = sum((PALETTE[i][k]-PALETTE[bg][k])**2 for k in range(3))
            return 1 if df <= db else 0
        bits = 0
        for c in range(8):
            bits = (bits << 1) | snap(idxs[c])
        pat.append(bits)
        col.append((fg << 4) | bg)
    return tuple(pat), tuple(col)

def carr(name, data):
    body = ",".join(str(b) for b in data)
    return f"const u8 {name}[{len(data)}]={{{body}}};\n"

def convert(path, name):
    im = Image.open(path).convert("RGB")
    w, h = im.size
    if w % 8 or h % 8:
        sys.exit(f"image {w}x{h} must be a multiple of 8 in both dimensions")
    px = im.load()
    tw, th = w // 8, h // 8
    uniq = {}           # (pattern,colour) -> tile index
    patterns, colours, namemap = [], [], []
    for ty in range(th):
        for tx in range(tw):
            key = tile_bytes(px, tx, ty)
            if key not in uniq:
                uniq[key] = len(uniq)
                patterns.extend(key[0])
                colours.extend(key[1])
            namemap.append(uniq[key])
    return dict(tw=tw, th=th, ntiles=len(uniq), patterns=patterns, colours=colours, name=namemap)

def roundtrip_ok(path, r):
    """Decode the tileset back and confirm it matches the tool's own quantisation
    (a stable golden check: convert is deterministic and its own inverse)."""
    im = Image.open(path).convert("RGB"); px = im.load()
    for ty in range(r["th"]):
        for tx in range(r["tw"]):
            want = tile_bytes(px, tx, ty)
            idx = r["name"][ty*r["tw"] + tx]
            got = (tuple(r["patterns"][idx*8:idx*8+8]), tuple(r["colours"][idx*8:idx*8+8]))
            if got != want:
                return False
    return True

def main():
    argv = [a for a in sys.argv[1:] if a != "--zx0"]
    zx0 = "--zx0" in sys.argv[1:]
    if len(argv) < 2:
        sys.exit("usage: img2tiles.py <in.png> <name> [out.h] [--zx0]")
    path, name = argv[0], argv[1]
    out = argv[2] if len(argv) > 2 else name + "_tiles.h"
    r = convert(path, name)
    assert roundtrip_ok(path, r), "round-trip mismatch (tool bug)"
    pat_c, _ = zx0pack.emit(name, "pattern", r["patterns"], zx0)      # all three arrays are
    col_c, _ = zx0pack.emit(name, "colour", r["colours"], zx0)        # bulk -> packable with
    nam_c, _ = zx0pack.emit(name, "nametable", r["name"], zx0)        # --zx0
    lines = [
        f"// {out} -- GENERATED by img2tiles.py from {path} (do not edit).",
        f"// MSX SCREEN 2 tileset: {r['tw']}x{r['th']} tiles, {r['ntiles']} unique "
        f"(dedup {100 - 100*r['ntiles']//(r['tw']*r['th'])}% saved){', ZX0-packed' if zx0 else ''}.",
        '#include "types.h"', "",
        pat_c, col_c, nam_c,
        f"#define {name.upper()}_NTILES {r['ntiles']}",
        f"#define {name.upper()}_W {r['tw']}",
        f"#define {name.upper()}_H {r['th']}",
    ]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {r['tw']}x{r['th']} tiles, {r['ntiles']} unique "
          f"({len(r['patterns'])}B pattern + {len(r['colours'])}B colour + "
          f"{len(r['name'])}B nametable){' [ZX0-packed]' if zx0 else ''}, round-trip OK")

if __name__ == "__main__":
    main()
