#!/usr/bin/env python3
# img2sprites.py -- mvcz80 asset pipeline: convert a PNG sprite sheet into an MSX
# hardware-sprite pattern table (8x8 or 16x16), plus a per-sprite colour byte.
#
# MSX sprites are monochrome per pattern: each pixel is on (draw in the sprite's
# colour) or off (transparent). A pixel is OFF if it is transparent (alpha < 128) or,
# for images without alpha, pure black -- everything else is ON. The sprite's colour
# is the nearest TMS9918 palette index of its most-common lit pixel (for SCREEN 2
# sprite-mode-1 attribute bytes).
#
#   8x8  (size 0): 8 bytes/sprite, one per row, bit7 = leftmost pixel.
#   16x16 (size 1): 32 bytes/sprite in the MSX quadrant order TL, BL, TR, BR
#                   (each quadrant an 8x8 block of 8 bytes).
#
# Companion to img2tiles/img2bitmap; deterministic + dependency-light (Python+Pillow),
# golden-tested. Usage: img2sprites.py <in.png> <name> <size 8|16> [out.h]
import sys
from PIL import Image

# Standard TMS9918 16-colour palette (RGB); index 0 = transparent.
PALETTE = [
    (0, 0, 0), (0, 0, 0), (33, 200, 66), (94, 220, 120),
    (84, 85, 237), (125, 118, 252), (212, 82, 77), (66, 235, 245),
    (252, 85, 84), (255, 121, 120), (212, 193, 84), (230, 206, 128),
    (33, 176, 59), (201, 91, 186), (204, 204, 204), (255, 255, 255),
]

def nearest(rgb):
    r, g, b = rgb[:3]
    return min(range(1, 16), key=lambda i: (r-PALETTE[i][0])**2 + (g-PALETTE[i][1])**2 + (b-PALETTE[i][2])**2)

def lit(px, x, y):
    r, g, b, a = px[x, y]
    if a < 128:
        return False
    return not (r == 0 and g == 0 and b == 0)   # black == transparent for alpha-less art

def block8(px, ox, oy):
    """8 bytes for the 8x8 block at (ox,oy): one per row, bit7 = leftmost."""
    out = []
    for row in range(8):
        bits = 0
        for col in range(8):
            bits = (bits << 1) | (1 if lit(px, ox + col, oy + row) else 0)
        out.append(bits)
    return out

def sprite_colour(px, ox, oy, size):
    counts = {}
    for y in range(size):
        for x in range(size):
            if lit(px, ox + x, oy + y):
                c = nearest(px[ox + x, oy + y])
                counts[c] = counts.get(c, 0) + 1
    if not counts:
        return 1   # empty sprite -> black
    return sorted(counts, key=lambda c: (-counts[c], c))[0]

def carr(name, data):
    return f"const u8 {name}[{len(data)}]={{{','.join(str(b) for b in data)}}};\n"

def convert(path, size):
    if size not in (8, 16):
        sys.exit("size must be 8 or 16")
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    if w % size or h % size:
        sys.exit(f"image {w}x{h} must be a multiple of {size} in both dimensions")
    px = im.load()
    sw, sh = w // size, h // size
    pattern, colour = [], []
    for sy in range(sh):
        for sx in range(sw):
            ox, oy = sx * size, sy * size
            if size == 8:
                pattern.extend(block8(px, ox, oy))
            else:
                # MSX 16x16 quadrant order: TL, BL, TR, BR
                pattern.extend(block8(px, ox,     oy))
                pattern.extend(block8(px, ox,     oy + 8))
                pattern.extend(block8(px, ox + 8, oy))
                pattern.extend(block8(px, ox + 8, oy + 8))
            colour.append(sprite_colour(px, ox, oy, size))
    return dict(size=size, count=sw * sh, sw=sw, sh=sh, pattern=pattern, colour=colour)

def main():
    if len(sys.argv) < 4:
        sys.exit("usage: img2sprites.py <in.png> <name> <size 8|16> [out.h]")
    path, name, size = sys.argv[1], sys.argv[2], int(sys.argv[3])
    out = sys.argv[4] if len(sys.argv) > 4 else name + "_sprites.h"
    r = convert(path, size)
    U = name.upper()
    lines = [
        f"// {out} -- GENERATED by img2sprites.py from {path} (do not edit).",
        f"// MSX {r['size']}x{r['size']} sprite bank: {r['count']} sprites "
        f"({len(r['pattern'])} pattern bytes).",
        '#include "types.h"', "",
        carr(name + "_pattern", r["pattern"]),
        carr(name + "_colour", r["colour"]),
        f"#define {U}_COUNT {r['count']}",
        f"#define {U}_SIZE {r['size']}",
    ]
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {r['count']} {r['size']}x{r['size']} sprites, "
          f"{len(r['pattern'])}B pattern + {len(r['colour'])}B colour")

if __name__ == "__main__":
    main()
