#!/usr/bin/env bash
# mb14blob.sh — regenerate the MoonBlaster module's GENERATED headers (all checked in):
#
#   lib/ext/moonblaster_bin.h        player binary + entry/variable addresses
#   docs/examples/moonblaster_song.h bundled example song  (assets/EXAMP1.MBM)
#   docs/examples/moonblaster_kit.h  sample-kit fragment    (assets/EXAMPLE.MBK)
#
# Maintainer-only: needs pasmo (https://pasmo.speccy.org). Consumers never run this —
# the generated headers are committed, so the library builds with plain SDCC.
#
# THE GATE: the player assembles from lib/ext/moonblaster_player.asm with its mapper
# writes neutralised (out (0FEh),a -> nop nop: the RESIDENT-song configuration, in which
# the whole 25-song regression suite was run). The result must be BYTE-IDENTICAL to the
# verified build — enforced by sha256. If you edit moonblaster_player.asm, this script
# will refuse to emit a blob until you have re-verified and updated REF_SHA. That is
# intentional: read the RULES FOR MODIFYING THIS FILE header in the .asm first.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASMO="${PASMO:-$(command -v pasmo || echo /home/remco/tools/pasmo)}"
SRC="$ROOT/lib/ext/moonblaster_player.asm"

# sha256 of the verified binary: the exact bytes that passed the 25-song
# chip-state-equivalence suite (experiments/mb14-irqtime, opt9 build).
REF_SHA="f815196eed681a22943635bf5c38eaafa2f5c1d27661948a20137fa38971567d"
REF_SIZE=5392

W=$(mktemp -d); trap 'rm -rf "$W"' EXIT

# resident-song configuration: drop the mapper page-2 switches (see moonblaster.h)
sed -E 's/^([[:space:]]*)out[[:space:]]*\(0feh\),a.*/\1nop\n\1nop/I' "$SRC" > "$W/mb.asm"
"$PASMO" "$W/mb.asm" "$W/mb.bin" "$W/mb.sym"

GOT_SHA=$(sha256sum "$W/mb.bin" | cut -d' ' -f1)
GOT_SIZE=$(wc -c < "$W/mb.bin")
if [ "$GOT_SHA" != "$REF_SHA" ] || [ "$GOT_SIZE" != "$REF_SIZE" ]; then
	echo "GATE FAIL: assembled player is not the verified binary" >&2
	echo "  got  sha256=$GOT_SHA size=$GOT_SIZE" >&2
	echo "  want sha256=$REF_SHA size=$REF_SIZE" >&2
	echo "Re-run the regression suite before updating REF_SHA (see header of this script)." >&2
	exit 1
fi

sym() { awk -v s="$1" '$1==s && $2=="EQU" {gsub(/H$/,"",$3); sub(/^0+/,"",$3); print "0x"$3}' "$W/mb.sym"; }
need() { v=$(sym "$1"); [ -n "$v" ] || { echo "SYM MISSING: $1" >&2; exit 1; }; echo "$v"; }

CHIPS=$(need chips);  BUSPLY=$(need busply); MUSPGE=$(need muspge); MUSADR=$(need musadr)
POS=$(need pos);      STEP=$(need step);     STEPBF=$(need stepbf)
STRMUS=$(need strmus); STPMUS=$(need stpmus); CNTMUS=$(need cntmus)
FADING=$(need fading); FADSPD=$(need fadspd); LASPL1=$(need laspl1)

# the public interface addresses are load-bearing (documented, and what hosts poke):
# refuse to emit if the layout ever drifts.
[ "$CHIPS" = "0xB000" ] && [ "$BUSPLY" = "0xB001" ] && [ "$MUSADR" = "0xB003" ] \
	&& [ "$STRMUS" = "0xB017" ] || { echo "INTERFACE DRIFT: entry addresses moved" >&2; exit 1; }

emit_array() { # emit_array <file> <cname>  (bytes on stdin via file)
	python3 - "$1" "$2" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
name = sys.argv[2]
print(f"static const unsigned char {name}[{len(data)}] = {{")
for i in range(0, len(data), 16):
    print("\t" + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",")
print("};")
PY
}

BIN_H="$ROOT/lib/ext/moonblaster_bin.h"
{
	echo "// moonblaster_bin.h -- GENERATED by tools/mb14blob.sh. DO NOT EDIT."
	echo "// Source: lib/ext/moonblaster_player.asm, assembled in the resident-song"
	echo "// configuration. sha256(payload) = $REF_SHA"
	echo "// These bytes are BYTE-IDENTICAL to the build that passed the 25-song"
	echo "// chip-state-equivalence regression suite (see docs/Sound-MoonBlaster.md)."
	echo "#ifndef MSXMVL_EXT_MOONBLASTER_BIN_H"
	echo "#define MSXMVL_EXT_MOONBLASTER_BIN_H"
	echo ""
	echo "#define MOONBLASTER_ORG      0xB000u  // fixed load address (must not change)"
	echo "#define MOONBLASTER_SIZE     ${REF_SIZE}u   // bytes; player occupies 0xB000-0xC50F"
	echo ""
	echo "// public interface of the replayer (fixed addresses, original mbplay layout)"
	echo "#define MOONBLASTER_CHIPS    ${CHIPS}u  // u8: 0=MSX-Audio 1=MSX-Music 2=stereo"
	echo "#define MOONBLASTER_BUSPLY   ${BUSPLY}u  // u8: 0=silent, 255=playing"
	echo "#define MOONBLASTER_MUSPGE   ${MUSPGE}u  // u8: unused in resident configuration"
	echo "#define MOONBLASTER_MUSADR   ${MUSADR}u  // u16: address of the loaded .MBM"
	echo "#define MOONBLASTER_POS      ${POS}u  // u8: current position counter"
	echo "#define MOONBLASTER_STEP     ${STEP}u  // u8: current step within the pattern"
	echo "#define MOONBLASTER_STEPBF   ${STEPBF}u  // u8[13]: decoded step buffer"
	echo "#define MOONBLASTER_STRMUS   ${STRMUS}u  // call: start music (installs H.TIMI hook)"
	echo "#define MOONBLASTER_STPMUS   ${STPMUS}u  // call: stop/pause (removes hook, silences)"
	echo "#define MOONBLASTER_CNTMUS   ${CNTMUS}u  // call: continue after stop/pause"
	echo "#define MOONBLASTER_FADING   ${FADING}u  // u8: write 255 to start a fade-out"
	echo "#define MOONBLASTER_FADSPD   ${FADSPD}u  // u8: fade speed, 1=fastest 255=slowest"
	echo "#define MOONBLASTER_LASPL1   ${LASPL1}u  // u8[9*25]: per-channel state records"
	echo ""
	emit_array "$W/mb.bin" "MOONBLASTER_BIN"
	echo ""
	echo "#endif // MSXMVL_EXT_MOONBLASTER_BIN_H"
} > "$BIN_H"
echo "wrote $BIN_H"

# --- bundled example song + sample kit --------------------------------------
# EXAMP1.MBM: "Example Song -- C.v/d Geest", from the MoonBlaster 1.4 disk; one of
# the 25 songs of the regression suite (so this exact file is oracle-verified).
# EXAMPLE.MBK: its matching sample kit (56-byte block table + 32768 bytes of Y8950
# ADPCM data). The ROM example embeds only the first KIT_FRAG bytes of ADPCM data;
# real programs load the whole file (see docs/Sound-MoonBlaster.md).
SONG="$ROOT/docs/examples/assets/EXAMP1.MBM"
KIT="$ROOT/docs/examples/assets/EXAMPLE.MBK"
KIT_FRAG=1024

SONG_H="$ROOT/docs/examples/moonblaster_song.h"
{
	echo "// moonblaster_song.h -- GENERATED by tools/mb14blob.sh from assets/EXAMP1.MBM."
	echo "// \"Example Song\" by C.v/d Geest (MoonBlaster 1.4 disk), included with permission."
	echo "// This exact file is one of the 25 songs of the replayer's regression suite."
	emit_array "$SONG" "MB_SONG_EXAMP1"
} > "$SONG_H"
echo "wrote $SONG_H"

head -c $((56 + KIT_FRAG)) "$KIT" > "$W/kitfrag.bin"
KIT_H="$ROOT/docs/examples/moonblaster_kit.h"
{
	echo "// moonblaster_kit.h -- GENERATED by tools/mb14blob.sh from assets/EXAMPLE.MBK."
	echo "// First $KIT_FRAG ADPCM data bytes only (a 16 KB example ROM cannot hold the full"
	echo "// 32 KB kit); real programs load assets/EXAMPLE.MBK from disk and pass"
	echo "// MOONBLASTER_KIT_FULL as the length."
	echo "#define MB_KIT_FRAG_LEN ${KIT_FRAG}u"
	emit_array "$W/kitfrag.bin" "MB_KIT_EXAMPLE_FRAG"
} > "$KIT_H"
echo "wrote $KIT_H"
