#!/usr/bin/env bash
# mbwblob.sh -- regenerate lib/ext/moonblaster_wave_bin.h from the committed replayer
# source lib/ext/moonblaster_wave_player.asm. Maintainer-only (needs pasmo); the
# generated header is checked in, so consumers build with plain SDCC.
#
# The RESIDENT-song configuration: the song lives in the visible 64 KB address space
# (no memory-mapper paging), so the replayer's page-2 bank switches are neutralised --
# selbank_FE/curbank_FE are patched to an immediate RET. The song must stay resident
# while it plays (the replayer reads it from the interrupt). See moonblaster_wave.h.
#
# Also neutralised: start_mus_cnt (the H.TIMI hook install). The replayer's own hook is
# an interslot RST 30h, which requires the BIOS in page 0 -- true in a ROM game, but NOT
# under MSX-DOS (page 0 is RAM there), where it crashes. So start_music does init only
# (no hook, no EI) and the C module installs its own direct, page-0-agnostic hook that
# stop_music still tears down via old_int. See moonblaster_wave.c.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASMO="${PASMO:-$(command -v pasmo || echo /home/remco/tools/pasmo)}"
SRC="$ROOT/lib/ext/moonblaster_wave_player.asm"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT

"$PASMO" --nocase "$SRC" "$W/mbw.bin" "$W/mbw.sym"
sym() { awk -v s="$1" 'toupper($1)==toupper(s) && $2=="EQU" {gsub(/H$/,"",$3); sub(/^0+/,"",$3); print "0x"$3}' "$W/mbw.sym"; }

ORG=0x4000
SIZE=$(wc -c < "$W/mbw.bin")
SEL=$(sym selbank_FE); CUR=$(sym curbank_FE); SMC=$(sym start_mus_cnt)

# resident config: patch selbank_FE + curbank_FE (mapper switches) and start_mus_cnt
# (interslot hook install) first byte -> 0xC9 (RET). The module installs its own hook.
python3 - "$W/mbw.bin" "$SEL" "$CUR" "$SMC" <<'PY'
import sys
p = sys.argv[1]
d = bytearray(open(p,'rb').read())
for a in sys.argv[2:]:
    d[int(a,16) - 0x4000] = 0xC9   # RET
open(p,'wb').write(d)
PY

emit_array() {
	# $1 = binary, $2 = C name, $3 = storage keyword ("const" for a definition)
	python3 - "$1" "$2" "$3" <<'PY'
import sys
data = open(sys.argv[1],'rb').read(); name = sys.argv[2]; kw = sys.argv[3]
print(f"{kw} unsigned char {name}[{len(data)}] = {{")
for i in range(0, len(data), 16):
    print("\t" + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",")
print("};")
PY
}

SHA=$(sha256sum "$W/mbw.bin" | cut -d' ' -f1)

# TWO generated files, because the blob (16 KB) must be relocated to 0x4000 -- and
# under MSX-DOS the .COM image reaches PAST 0x4000, so a blob placed among the wrapper
# functions would sit in the overwrite zone and Init would destroy the very code that
# drives it. The blob is therefore defined LAST (its data header is #included at the
# BOTTOM of moonblaster_wave.c), which keeps every wrapper below 0x4000. The interface
# header (defines + extern decl) is #included at the top so the wrappers can compile.
OUT="$ROOT/lib/ext/moonblaster_wave_bin.h"
DAT="$ROOT/lib/ext/moonblaster_wave_bin_data.h"
{
	echo "// moonblaster_wave_bin.h -- GENERATED by tools/mbwblob.sh. DO NOT EDIT."
	echo "// Source: lib/ext/moonblaster_wave_player.asm, resident-song configuration"
	echo "// (selbank_FE/curbank_FE/start_mus_cnt -> RET). sha256(payload) = $SHA"
	echo "// Interface only: #defines + a forward declaration of the blob. The blob DATA"
	echo "// lives in moonblaster_wave_bin_data.h, #included at the BOTTOM of the .c so it"
	echo "// links above the wrappers (which Init's copy-to-0x4000 must not overwrite)."
	echo "#ifndef MSXMVL_EXT_MOONBLASTER_WAVE_BIN_H"
	echo "#define MSXMVL_EXT_MOONBLASTER_WAVE_BIN_H"
	echo ""
	echo "#define MBWAVE_ORG        ${ORG}u   // load address (16 KB replayer, 0x4000-0x7E8D)"
	echo "#define MBWAVE_SIZE       ${SIZE}u  // bytes to copy from the blob to MBWAVE_ORG"
	echo ""
	echo "// replayer interface (fixed addresses; workspace is at 0xDA00, above the code)"
	echo "#define MBWAVE_START      $(sym start_music)u  // call: init OPL4 + song, begin (no hook)"
	echo "#define MBWAVE_STOP       $(sym stop_music)u  // call: stop/pause, silence"
	echo "#define MBWAVE_CONT       $(sym cont_music)u  // call: continue after stop/pause"
	echo "#define MBWAVE_PLAYINT    $(sym play_int)u  // the per-interrupt replay routine"
	echo "#define MBWAVE_OLDINT     $(sym old_int)u  // play_int chain tail (module writes RET here)"
	echo "#define MBWAVE_BUSY       $(sym play_busy)u  // u8: 0=silent, nonzero=playing"
	echo "#define MBWAVE_SONGADR    $(sym songdata_adres)u  // u16: song body address (file+6)"
	echo "#define MBWAVE_BANK1      $(sym songdata_bank1)u  // u8: song mapper segment (resident: unused)"
	echo "#define MBWAVE_POS        $(sym play_pos)u  // u8: current position"
	echo "#define MBWAVE_STEP       $(sym play_step)u  // u8: current step in the pattern"
	echo ""
	echo "extern const unsigned char MBWAVE_BIN[MBWAVE_SIZE];  // defined in *_bin_data.h"
	echo ""
	echo "#endif // MSXMVL_EXT_MOONBLASTER_WAVE_BIN_H"
} > "$OUT"
{
	echo "// moonblaster_wave_bin_data.h -- GENERATED by tools/mbwblob.sh. DO NOT EDIT."
	echo "// The pre-assembled 16 KB replayer blob. #included ONCE, at the BOTTOM of"
	echo "// moonblaster_wave.c, so it links after every wrapper function (see *_bin.h)."
	echo "// sha256(payload) = $SHA"
	echo ""
	emit_array "$W/mbw.bin" "MBWAVE_BIN" "const"
} > "$DAT"
echo "wrote $OUT + $DAT ($SIZE B blob, sha ${SHA:0:16})"
